export default {
  darkMode: "class",
  content: [
    "./src/**/*.{html,ts}"
  ],
  theme: {
        extend: {
          "colors": {
                  "on-secondary": "#ffffff",
                "on-primary-fixed-variant": "#324c3e",
                "on-tertiary-container": "#b8ad97",
                "surface-container-low": "#f6f3ee",
                "secondary-fixed": "#ffdbcf",
                "surface-tint": "#496455",
                "on-surface-variant": "#424844",
                "on-error": "#ffffff",
                "on-tertiary": "#ffffff",
                "surface-variant": "#e5e2dd",
                "on-primary-fixed": "#062014",
                "inverse-surface": "#31302d",
                "on-surface": "#1c1c19",
                "on-tertiary-fixed": "#211b0c",
                "tertiary-container": "#484130",
                "surface-bright": "#fcf9f4",
                "primary-fixed-dim": "#b0cdbb",
                "background": "#fcf9f4",
                "surface-dim": "#dcdad5",
                "secondary-container": "#ff9973",
                "surface-container-lowest": "#ffffff",
                "on-tertiary-fixed-variant": "#4d4634",
                "on-secondary-fixed-variant": "#793013",
                "inverse-on-surface": "#f3f0eb",
                "error-container": "#ffdad6",
                "primary-fixed": "#ccead6",
                "on-background": "#1c1c19",
                "primary": "#173124",
                "surface-container": "#f0ede8",
                "secondary": "#974728",
                "on-primary-container": "#98b5a3",
                "inverse-primary": "#b0cdbb",
                "tertiary": "#312b1b",
                "tertiary-fixed-dim": "#d1c5ae",
                "surface": "#fcf9f4",
                "error": "#ba1a1a",
                "outline-variant": "#c2c8c2",
                "tertiary-fixed": "#ede1c9",
                "on-secondary-container": "#772f12",
                "on-secondary-fixed": "#380d00",
                "on-primary": "#ffffff",
                "surface-container-highest": "#e5e2dd",
                "surface-container-high": "#ebe8e3",
                "primary-container": "#2d4739",
                "on-error-container": "#93000a",
                "outline": "#727973",
                "secondary-fixed-dim": "#ffb59b",
                "primary-container": "#2d4739",
                        "on-secondary-fixed": "#380d00",
                        "surface-container-high": "#ebe8e3",
                        "secondary": "#974728",
                        "on-primary-fixed-variant": "#324c3e",
                        "on-primary": "#ffffff",
                        "surface-container-highest": "#e5e2dd",
                        "surface-dim": "#dcdad5",
                        "on-tertiary-fixed-variant": "#4d4634",
                        "on-error-container": "#93000a",
                        "inverse-on-surface": "#f3f0eb",
                        "background": "#fcf9f4",
                        "on-error": "#ffffff",
                        "surface-variant": "#e5e2dd",
                        "on-secondary": "#ffffff",
                        "on-primary-container": "#98b5a3",
                        "tertiary-fixed-dim": "#d1c5ae",
                        "secondary-fixed-dim": "#ffb59b",
                        "on-tertiary": "#ffffff",
                        "tertiary-fixed": "#ede1c9",
                        "on-primary-fixed": "#062014",
                        "on-surface": "#1c1c19",
                        "on-tertiary-fixed": "#211b0c",
                        "surface-container": "#f0ede8",
                        "surface-tint": "#496455",
                        "primary-fixed-dim": "#b0cdbb",
                        "error": "#ba1a1a",
                        "tertiary-container": "#484130",
                        "outline": "#727973",
                        "tertiary": "#312b1b",
                        "inverse-surface": "#31302d",
                        "secondary-fixed": "#ffdbcf",
                        "inverse-primary": "#b0cdbb",
                        "on-background": "#1c1c19",
                        "on-secondary-fixed-variant": "#793013",
                        "on-surface-variant": "#424844",
                        "surface": "#fcf9f4",
                        "on-tertiary-container": "#b8ad97",
                        "outline-variant": "#c2c8c2",
                        "surface-container-lowest": "#ffffff",
                        "secondary-container": "#ff9973",
                        "error-container": "#ffdad6",
                        "primary": "#173124",
                        "surface-bright": "#fcf9f4",
                        "primary-fixed": "#ccead6",
                        "surface-container-low": "#f6f3ee",
                        "on-secondary-container": "#772f12"
          },
          
        
      
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px"
      },
      fontFamily: {
                    "headline": ["Manrope"],
                    "body": ["Plus Jakarta Sans"],
                    "label": ["Plus Jakarta Sans"]
      }
    },
  },
  plugins: [],
}